name: AppEstoqueMP
description: "Teste de Projeto Flutter"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_custom_clippers: ^2.1.0
  barcode_scan2: ^4.3.3
  http: ^1.2.2
  shared_preferences: ^2.3.0
  sqflite: any
  path: any
  path_provider: any
  cupertino_icons: ^1.0.6
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_copyright_kingejoe.png
    - assets/logo_app.png



